apiVersion: batch/v1
kind: Job
metadata:
  name: cyclegan-training-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: pap-processing
          image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
          env:
            - name: REPO_PATH
              value: /app/3d_cyclegan
          command:
            - "bash"
            - "-c"
          args:
            - |
              echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
              sudo mkdir -p /datam/cycleganfinaloutput
              sudo mkdir -p /datam/cycleganfinaloutput/t2_flair/
              sudo mkdir -p /datam/cycleganfinaloutput/t2_flair/checkpoints/
              sudo mkdir -p /datam/cycleganfinaloutput/t2_flair/logs/
              sudo chmod -R 777 /datam/cycleganfinaloutput
              cd /app
              git clone --single-branch -b main https://github.com/dan-hanson/3d_cyclegan
              cd ${REPO_PATH}
              echo "Installing dependencies with pip..."
              pip install torchsummary torchio torchmetrics matplotlib tensorboard
              echo "Dependencies installed, copying tar from pvc..."
              cp /datam/brats128_processed_20250502_040703.tar.gz .
              echo "Data copied! Extracting..."
              tar -xzf brats128_processed_20250502_040703.tar.gz
              echo "Done extracting."
              echo "Starting training..."
              python3 train_cycleGAN.py \
                --mapping_type t1_contrast \
                --data_dir processed/brats128_split/train/images \
                --val_data_dir processed/brats128_split/val/images \
                --output_base_dir /datam/cycleganfinaloutput \
                --epochs 200 \
                --use_tb
              echo "Training finished. Listing output directory contents:"
              ls -lh /datam/cycleganfinaloutput/
              echo 'Listing contents of mapping-specific subdirectories (if they exist):'
              ls -lh /datam/cycleganfinaloutput/t2_flair/ || echo "Directory not found"
              ls -lh /datam/cycleganfinaloutput/t2_flair/checkpoints/ || echo "Directory not found"
              ls -lh /datam/cycleganfinaloutput/t2_flair/logs/ || echo "Directory not found"
          volumeMounts:
            - name: git-repo
              mountPath: /app
            - name: brats-datam
              mountPath: /datam
            - name: dshm
              mountPath: /dev/shm
          resources:
            limits:
              memory: 30Gi
              cpu: "24"
              nvidia.com/a100: "1"
            requests:
              memory: 25Gi
              cpu: "20"
              nvidia.com/a100: "1"
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: brats-datam
          persistentVolumeClaim:
            claimName: brats-data-m
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
      restartPolicy: Never