apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brats-data-m
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi